name: CI
on:
  push: { branches: ["*"] }
  pull_request: { branches: ["*"] }
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      # ВАЖНО: НИКАКИХ внешних npm-install actions. Только явный npm install.
      - name: Install deps (no ci)
        run: npm install --no-audit --no-fund

      - name: Lint
        run: npm run lint || true

      - name: Typecheck
        run: npm run typecheck || true

      - name: Unit / Coverage
        run: npm run test:ci || npm test

      - name: Static analysis (knip + madge)
        run: npm run quality:check

      - name: Performance budgets (size-limit + Lighthouse)
        run: npm run perf:check
