name: CI
on:
  push: { branches: ["*"] }
  pull_request: { branches: ["*"] }
jobs:
  sentinel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure no auto-install actions
        shell: bash
        run: |
          set -e
          # Ищем ТОЛЬКО реальные вызовы экшена (ключ uses: ...)
          if egrep -R -n '^[[:space:]]*uses:[[:space:]]*bahmutov/npm-install@' .github/workflows >/tmp/_forbidden.txt; then
            echo "::group::Forbidden auto-install usages"
            cat /tmp/_forbidden.txt
            echo "::endgroup::"
            echo "::error::Remove 'bahmutov/npm-install' actions — they force 'npm ci' before lock sync"
            exit 1
          fi

  build-test:
    runs-on: ubuntu-latest
    needs: [sentinel]
    env:
      HUSKY: "0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      # 1) Синхронизируем lock с package.json (без lifecycle скриптов)
      - name: Sync lockfile (no scripts)
        run: npm install --package-lock-only --no-audit --no-fund --ignore-scripts

      # 2) Строгая установка без скриптов; fallback на install
      - name: Clean install (ci, ignore scripts)
        run: npm ci --no-audit --no-fund --ignore-scripts || npm install --no-audit --no-fund --ignore-scripts

      # 3) Ручной postinstall-патч Next (если присутствует)
      - name: Postinstall (manual Next patch)
        run: |
          if [ -f scripts/patch-next.cjs ]; then node scripts/patch-next.cjs; fi

      - name: Lint
        run: npm run lint || true

      - name: Typecheck
        run: npm run typecheck || true

      - name: Unit / Coverage
        run: npm run test:ci || npm test

      - name: Static analysis (knip + madge)
        run: npm run quality:check

      - name: Performance budgets (size-limit + Lighthouse)
        run: npm run perf:check
