name: data-validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  data-validate:
    name: Data validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies (ci if lockfile, fallback otherwise)
        id: install_deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Lockfile present — running npm ci."
            npm ci --ignore-scripts --no-audit --no-fund
          else
            echo "No lockfile — running ephemeral npm install (no lock write)."
            npm i --ignore-scripts --no-audit --no-fund --no-save --package-lock=false --include=dev
          fi

      - name: Run data freshness checks
        run: |
          set -euo pipefail
          mkdir -p reports/logs
          bash data_validate.sh \
            --catalog data/catalog.yml \
            --raw-dir data/raw \
            --json-report reports/data-validation.json | tee reports/logs/data-freshness.log

      - name: Ensure validation log placeholders
        if: always()
        run: |
          mkdir -p reports/logs
          declare -A titles=(
            [great-expectations]="Great Expectations"
            [frictionless]="Frictionless"
            [duckdb]="DuckDB"
          )
          for key in "${!titles[@]}"; do
            logfile="reports/logs/${key}.log"
            if [[ ! -s "$logfile" ]]; then
              echo "${titles[$key]} validation output was not generated during this run." >"$logfile"
            fi
          done

      - name: Upload validation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-validation
          if-no-files-found: warn
          path: |
            reports/data-validation.json
            reports/logs
