name: Release Please
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please (manifest)
        uses: googleapis/release-please-action@v4
        with:
          # По умолчанию используем GITHUB_TOKEN.
          # Если добавишь персональный токен как секрет RELEASE_PLEASE_TOKEN,
          # можно заменить строку ниже на: token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
