name: Visual Snapshot Baselines
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to update baselines (PR head)"
        required: false
        default: ""

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      HUSKY: "0"
      NEXT_PUBLIC_APP_NAME: "Summa Vision"
      NEXT_PUBLIC_API_BASE_URL: "https://example.invalid"
      NEXT_PUBLIC_SITE_URL: "http://localhost:3010"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.inputs.branch || github.event.pull_request.head.sha || github.head_ref || github.ref_name }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Sync lockfile (no scripts)
        run: npm install --package-lock-only --no-audit --no-fund --ignore-scripts

      - name: Install deps (ignore scripts)
        run: npm ci --no-audit --no-fund --ignore-scripts || npm install --no-audit --no-fund --ignore-scripts

      - name: Postinstall (manual Next patch)
        run: |
          if [ -f scripts/patch-next.cjs ]; then node scripts/patch-next.cjs; fi

      - name: Prepare env for apps/web
        run: |
          mkdir -p apps/web
          cat > apps/web/.env.local <<'EOF_ENV'
          NEXT_PUBLIC_APP_NAME=Summa Vision
          NEXT_PUBLIC_API_BASE_URL=https://example.invalid
          NEXT_PUBLIC_SITE_URL=http://localhost:3010
          EOF_ENV

      - name: Install Playwright browsers (same version)
        run: npx -y playwright@1.48.0 install --with-deps chromium

      - name: Build site
        run: npm run web:build

      - name: Update snapshots (Playwright starts server)
        run: npx -y @playwright/test@1.48.0 test e2e/visual --update-snapshots

      - name: Commit baseline PNGs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -N "e2e/visual/**-snapshots/*.png" >/dev/null 2>&1 || true
          CHANGED=$(git status --porcelain | awk '/^ [AM] / && $0 ~ /\.png$/ {print $2}' | wc -l)
          if [ "$CHANGED" -eq 0 ]; then
            echo "No baseline PNG changes."
            exit 0
          fi

          git add e2e/visual/**-snapshots/*.png
          git commit -m "test(visual): update baseline snapshots via Actions"
          git push origin HEAD:${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref_name }}
