name: Visual Snapshot Baselines (Sync)
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "PR head branch to update baselines"
        required: false
        default: ""

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      HUSKY: "0"
      NEXT_PUBLIC_APP_NAME: "Summa Vision"
      NEXT_PUBLIC_API_BASE_URL: "https://example.invalid"
      NEXT_PUBLIC_SITE_URL: "http://localhost:3000"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Resolve target branch
        id: br
        shell: bash
        run: |
          set -e
          BR="${{ github.event.inputs.branch }}"
          if [ -z "$BR" ]; then
            if [ -n "${{ github.head_ref }}" ]; then BR="${{ github.head_ref }}"; else BR="${{ github.ref_name }}"; fi
          fi
          echo "branch=$BR" >> "$GITHUB_OUTPUT"
          git fetch origin "$BR:$BR" --depth=1 || (echo "::error::Branch '$BR' not found"; exit 1)
          git switch "$BR"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm install --package-lock-only --no-audit --no-fund --ignore-scripts
      - run: npm ci --no-audit --no-fund --ignore-scripts || npm install --no-audit --no-fund --ignore-scripts
      - name: Postinstall (manual Next patch)
        run: |
          if [ -f scripts/patch-next.cjs ]; then node scripts/patch-next.cjs; fi
      - name: Prepare env for apps/web
        run: |
          mkdir -p apps/web
          cat > apps/web/.env.local <<'EOF'
          NEXT_PUBLIC_APP_NAME=Summa Vision
          NEXT_PUBLIC_API_BASE_URL=https://example.invalid
          NEXT_PUBLIC_SITE_URL=http://localhost:3000
          EOF
      - name: Install Playwright browsers
        run: npx -y playwright@1.48.0 install --with-deps chromium
      - name: Build site
        run: npm run web:build
      - name: Update snapshots (generate PNG)
        run: |
          npm run web:start:ci & sleep 6
          npx -y playwright@1.48.0 test e2e/visual --update-snapshots
      - name: Commit baseline PNGs to PR branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -N "e2e/visual/**-snapshots/*.png" >/dev/null 2>&1 || true
          CHANGED=$(git status --porcelain | awk '/^ [AM] / && $0 ~ /\.png$/ {print $2}' | wc -l)
          if [ "$CHANGED" -eq 0 ]; then
            echo "No baseline PNG changes."
            exit 0
          fi
          git add e2e/visual/**-snapshots/*.png
          git commit -m "test(visual): update baseline snapshots via Actions"
          git push origin HEAD:${{ steps.br.outputs.branch }}
